### ISSUE TITLE
can`t find ffhq_weights_stylegan3.pkl

### ISSUE THREAD

**Issue by mimzzzz** [IGLICT/DeepFaceVideoEditing#1]
ffhq_weights_stylegan3.pkl == jt_stylegan3_ffhq_weights_t.pkl ? 

load this model error, RuntimeError: Ran out of input

**Comment by ty625911724** [comment]
"ffhq_weights_stylegan3.pkl" is generated after the PTI step. 

Maybe you can preprocess videos and run PTI training, then load the specific StyleGAN3 model.

**Comment by mimzzzz** [comment]
> 
Thank you. It's running normally
