### ISSUE TITLE
How to draw sketch to make someone close his/her mouth?

### ISSUE THREAD

**Issue by whhamber** [IGLICT/DeepFaceVideoEditing#3]
I have tried several kinds of sketch, but I failed to make the person close his/her mouth. 
Have you ever succeed in making it? If so, would you please share the sketch with me? If not, I wonder does the model have such ability?
Thanks a lot.

**Comment by whhamber** [comment]
I have made it. The key point is draw thin lines as you can. The thick line between two lips will guide the model to generate tooth instead of closing mouth.

**Comment by ooochen-30** [comment]
> I have made it. The key point is draw thin lines as you can. The thick line between two lips will guide the model to generate tooth instead of closing mouth.

hello  may i ask how do u make the sketch, i try to make it by drawing sofeware. but while i let it edit(python run_editing.py) it happened the following error.can u give me some suggest?
=========================================
warp mask: 0/1
Traceback (most recent call last):
  File "run_editing.py", line 188, in <module>
    predictions = make_mask_animation(source_image, mask_image, driving_video, generator, kp_detector, relative=False, adapt_movement_scale=False)
  File "/home/xdy/code/DeepFaceVideoEditing-main/warp_mask.py", line 64, in make_mask_animation
    mask = jt.array(mask_image[np.newaxis].astype(np.float32)).permute(0, 3, 1, 2)
  File "/home/xdy/anaconda3/envs/jittor/lib/python3.8/site-packages/jittor/__init__.py", line 569, in transpose
    return origin_transpose(x, dim)
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.ops.transpose)).

Types of your inputs are:
 self	= module,
 args	= (Var, tuple, ),

The function declarations are:
 VarHolder* transpose(VarHolder* x,  NanoVector axes=NanoVector())

Failed reason:[f 0202 14:24:00.800278 36 cutt_transpose_op.cc:40] Check failed axes.size()(4) == xdim(3)
